baseURL = "https://blog.nmrs.fi"
defaultContentLanguage = "en"
languageCode = "en"
title = "Portfolio"
theme = "PaperMod"
tag = "tags"

[menu]
    [[menu.main]]
    identifier = "About me"
    name = "About me"
    url = "/about"
    weight = 1

    [[menu.main]]
    identifier = "Posts"
    url = "/posts"
    pre = ""
    post = ""
    name = "Posts"
    weight = 2

    [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 3